
const uint OBJECT_COUNT = 65536;
const uint WORLD_SIZE = 500;
const uint MAX_GROUP_COUNT = 1024;
const uint CHUNK_COUNT_SIDE = 32;
const uint CHUNK_COUNT = CHUNK_COUNT_SIDE * CHUNK_COUNT_SIDE * CHUNK_COUNT_SIDE;
const uint MAX_OBJECTS_PER_CHUNK = OBJECT_COUNT * 4 / CHUNK_COUNT + 1;
const uint SORT_THREAD_COUNT = 64;
const uint SORT_OBJECT_COUNT = (OBJECT_COUNT + SORT_THREAD_COUNT - 1) / SORT_THREAD_COUNT;
const uint SORT_THREAD_OBJECT_PER_CHUNK = MAX_OBJECTS_PER_CHUNK / 4 + 1;
const uint OBJECT_UPDATE_COUNT = (OBJECT_COUNT + CHUNK_COUNT - 1) / CHUNK_COUNT;
const uint BLOCK_SIZE_Z = (CHUNK_COUNT + MAX_GROUP_COUNT - 1) / MAX_GROUP_COUNT;
const uint CHUNK_COUNT_SIDE_Z = CHUNK_COUNT_SIDE / BLOCK_SIZE_Z;

const float BOID_DIST_MAX = 31.0f;
const float BOID_DIST_MIN = 8.0f;
const float BOID_MAX_SPEED = 50.0f;
